"""Build and persist a local FAISS vector store for document chunks."""

from __future__ import annotations

import logging
from pathlib import Path

from langchain_core.documents import Document
from langchain_core.vectorstores import VectorStore

from src.ingestion.embeddings import (
    DEFAULT_EMBEDDING_MODEL,
    get_embedding_model,
)
from src.ingestion.splitter import load_and_split_documents

logger = logging.getLogger(__name__)
_LOGGER_CONFIGURED = False
_DEFAULT_INDEX_DIR = Path(__file__).resolve().parents[2] / "storage" / "faiss_index"


def _configure_logging() -> Path:
    """Write vector-store activity to ``logs/vectorstore.log``."""

    global _LOGGER_CONFIGURED
    log_path = Path(__file__).resolve().parents[2] / "logs" / "vectorstore.log"
    if not _LOGGER_CONFIGURED:
        log_path.parent.mkdir(parents=True, exist_ok=True)
        handler = logging.FileHandler(log_path, encoding="utf-8")
        handler.setFormatter(
            logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s")
        )
        logger.addHandler(handler)
        logger.setLevel(logging.INFO)
        _LOGGER_CONFIGURED = True
    return log_path


def create_vector_store(
    documents: list[Document],
    *,
    model_name: str = DEFAULT_EMBEDDING_MODEL,
) -> VectorStore:
    """Create a FAISS store from already-split LangChain documents."""

    if not documents:
        raise ValueError("Cannot create a vector store from zero documents")

    from langchain_community.vectorstores import FAISS

    _configure_logging()
    logger.info(
        "Creating FAISS vector store: documents=%d model=%s",
        len(documents),
        model_name,
    )
    store = FAISS.from_documents(
        documents,
        get_embedding_model(model_name),
    )
    logger.info("Created FAISS vector store: vectors=%d", store.index.ntotal)
    return store


def save_vector_store(
    store: VectorStore,
    index_dir: str | Path = _DEFAULT_INDEX_DIR,
) -> Path:
    """Persist a FAISS store and its LangChain document metadata."""

    target = Path(index_dir).expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)
    if not hasattr(store, "save_local"):
        raise TypeError("The supplied vector store does not support local persistence")

    store.save_local(str(target))
    logger.info("Saved FAISS vector store: vectors=%d path=%s", store.index.ntotal, target)
    return target


def load_vector_store(
    index_dir: str | Path = _DEFAULT_INDEX_DIR,
    *,
    model_name: str = DEFAULT_EMBEDDING_MODEL,
) -> VectorStore:
    """Load a previously saved FAISS store from disk."""

    from langchain_community.vectorstores import FAISS

    target = Path(index_dir).expanduser().resolve()
    index_file = target / "index.faiss"
    metadata_file = target / "index.pkl"
    if not index_file.is_file() or not metadata_file.is_file():
        raise FileNotFoundError(
            f"FAISS index is incomplete: expected {index_file} and {metadata_file}"
        )

    store = FAISS.load_local(
        str(target),
        get_embedding_model(model_name),
        # index.pkl is generated by save_vector_store in this project.
        allow_dangerous_deserialization=True,
    )
    logger.info("Loaded FAISS vector store: vectors=%d path=%s", store.index.ntotal, target)
    return store


def build_and_save_vector_store(
    data_dir: str | Path | None = None,
    index_dir: str | Path = _DEFAULT_INDEX_DIR,
    *,
    chunk_size: int = 1000,
    chunk_overlap: int = 200,
    strict: bool = False,
    model_name: str = DEFAULT_EMBEDDING_MODEL,
) -> VectorStore:
    """Load, split, embed, and persist all supported data files in FAISS."""

    _configure_logging()
    documents = load_and_split_documents(
        data_dir,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        strict=strict,
    )
    store = create_vector_store(documents, model_name=model_name)
    save_vector_store(store, index_dir)
    logger.info(
        "Completed FAISS build: chunks=%d vectors=%d path=%s",
        len(documents),
        store.index.ntotal,
        Path(index_dir).expanduser().resolve(),
    )
    return store


if __name__ == "__main__":
    store = build_and_save_vector_store()
    print(
        f"Stored {store.index.ntotal} vector(s) in storage/faiss_index. "
        "See logs/vectorstore.log for details."
    )


__all__ = [
    "build_and_save_vector_store",
    "create_vector_store",
    "load_vector_store",
    "save_vector_store",
]